import './index.css'
import { useState } from 'react'
import Button from '../Button/Button';
function Position() {
  const [scrollTop, setScrollTop] = useState(0);

  const handleScroll = event => {
    setScrollTop(event.currentTarget.scrollTop);
  };
  window.addEventListener('scroll', handleScroll);
  return (
    
    <div className='position-div' onScroll={handleScroll}>
        <Button text="Scroll arriba" visible={scrollTop > 300 ? true : false}/>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit, itaque asperiores quas amet at magnam quod harum dolor alias, voluptatem consectetur mollitia consequatur distinctio porro perspiciatis nulla nisi. Saepe, tempora?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni dicta qui amet sit, quas unde perspiciatis eveniet, iste quos consectetur, rem id impedit eligendi laudantium asperiores. Laborum natus totam magnam!
        In fugit debitis a nesciunt odio, mollitia praesentium amet possimus consequuntur sunt molestiae earum labore impedit officia corporis consequatur ipsa laudantium natus perferendis! Quibusdam, sapiente ipsa debitis aliquam voluptas officia?
        Aspernatur, obcaecati quia non, fuga labore blanditiis sapiente doloremque temporibus officia eligendi a? Optio eius dolores provident, reiciendis hic voluptatibus quis libero nobis maiores laboriosam, aliquid tempore, voluptatum cupiditate saepe!
        Veniam natus facere recusandae temporibus at deserunt velit, tempore corporis. Repellendus qui sint porro ratione asperiores deserunt illum iste animi ipsum quae consectetur et suscipit, obcaecati corporis eveniet quam? Quae?
        Nemo possimus dolorem ullam eum provident aspernatur incidunt labore eveniet dignissimos assumenda reiciendis ab beatae, cum magni cumque nobis natus porro expedita ad voluptates, fuga quibusdam culpa enim. Cupiditate, nesciunt!
        Explicabo optio voluptates est adipisci similique maxime porro dolores iusto. Enim quisquam ab tenetur, voluptas inventore obcaecati aperiam maxime in molestiae nemo mollitia incidunt, explicabo cum dolor repudiandae facere commodi.
        Ea, rem voluptas adipisci, vel animi odit saepe quam unde quibusdam illum doloribus incidunt error doloremque dolor iste dolorum at quod nulla porro? Corporis delectus, minus eum possimus dolores expedita.
        Voluptate id labore necessitatibus. Saepe doloremque molestias possimus ducimus, ea deserunt magni alias expedita veniam earum? Error vitae voluptate obcaecati, at rerum quas expedita nesciunt incidunt. Eum maxime pariatur nostrum.
        Doloremque error dolores quaerat velit? Repellendus amet quisquam quos animi eaque repellat sint, commodi obcaecati nobis labore, minima eius iure fuga debitis odio veniam inventore necessitatibus harum ad perferendis? Suscipit.
        Eveniet deleniti exercitationem excepturi facere cumque, ex optio culpa nobis pariatur nostrum eligendi libero ipsum doloribus minus officiis corrupti inventore magni vitae quasi consectetur necessitatibus delectus quidem, maiores aliquid. Dolorem.
        Quo, libero consequuntur accusantium tenetur voluptatum porro ad nisi omnis numquam ducimus magni esse nulla quisquam dolorem enim ipsa iusto eos aperiam deleniti, excepturi necessitatibus nostrum ipsam. Blanditiis, minima nobis.
        Consectetur esse reiciendis doloremque. At error corrupti aliquid laborum non architecto minima ad nam culpa corporis repellendus nesciunt assumenda aliquam nobis illum exercitationem commodi, rem aperiam iste incidunt quo. Quis?
        Illum saepe accusamus ipsam eum temporibus ea beatae voluptate blanditiis qui voluptatibus, iste delectus nulla eaque deserunt maiores. Nam doloribus itaque, delectus ad unde eveniet alias saepe placeat corrupti et.
        Omnis quam ipsam iusto enim aliquam autem voluptatum repellendus ut reprehenderit, quas, nemo tempora architecto voluptatibus doloremque nobis similique dolorum cum perspiciatis quos inventore distinctio blanditiis perferendis aspernatur sunt? Dolores?
        Commodi earum aliquam alias! Eveniet assumenda quos id accusamus nesciunt commodi laudantium doloribus ullam autem quaerat, aliquid, aspernatur recusandae velit? Possimus, neque! Autem iure deleniti nesciunt aspernatur totam iste ut?
        Et inventore doloremque vitae vero! Unde, aspernatur eius? A in tempora saepe unde blanditiis, tempore itaque neque libero repellendus corporis facere consequuntur dolorum vel sed quas impedit quaerat architecto ducimus.
        Quos, voluptatum? Corrupti quas, impedit beatae voluptas reprehenderit dolor dignissimos sequi eos iste itaque distinctio est repellat amet maiores atque qui! Sunt, at cum? Earum, unde. Quas voluptate vitae quidem.
        Praesentium recusandae a incidunt magni sint adipisci ad. Ab perspiciatis dicta fugit, recusandae dolores sed blanditiis id aut similique accusamus nisi magnam corporis necessitatibus vero nostrum eligendi architecto quia fuga?
        Aliquid itaque eligendi, in ut quidem quasi aut ratione facilis maiores repudiandae mollitia hic veritatis architecto odio natus quas. Aperiam omnis eos ea nam mollitia quo cumque, molestias debitis asperiores!
        Vel culpa reiciendis maxime minus dolor ea inventore quae commodi cupiditate reprehenderit quos expedita cumque quidem veritatis laudantium voluptates accusantium, modi, saepe temporibus qui ut a dignissimos veniam numquam. Perspiciatis.
        Eveniet cupiditate eos inventore voluptates qui, rem ipsam tenetur facilis cumque magni dolorum perferendis. Rem voluptatem quasi, voluptate quo vel nihil sapiente ad. Nam corrupti voluptatibus nisi optio amet autem.
        Delectus at earum repellendus? Impedit ut sit aliquid illo, aperiam vitae animi, perferendis eum natus ullam asperiores quod aspernatur iste at cum optio dolor, facere delectus! Voluptates iste consequuntur blanditiis!
        Consequatur vero in deserunt dignissimos totam, saepe voluptatibus voluptatem quibusdam quidem, corporis quis. Earum at neque nostrum, nulla tempore laborum et doloremque accusamus! Obcaecati quo ea, vero aliquam enim cupiditate.
        Officiis amet voluptates labore, necessitatibus minus blanditiis accusantium soluta ad repellendus, iusto sed neque in dolor laboriosam eligendi reiciendis veritatis dolores possimus voluptas quidem? Pariatur nobis deleniti nostrum aliquam consequuntur?
        Dolores, modi porro nisi magnam asperiores iure autem dolorem voluptate at officiis vel qui adipisci unde aut libero voluptatum expedita possimus quo ab officia fuga sapiente? Reprehenderit repellat dolore eaque.
        Vitae commodi laborum ex quisquam. Omnis eos provident hic enim doloribus! Error, eius placeat? Ducimus veniam tenetur saepe, veritatis totam ad quos, maxime velit consectetur enim magnam facilis quibusdam necessitatibus.
        Reiciendis nihil officia numquam ut aut quas velit voluptatum itaque esse a, error vitae necessitatibus placeat cumque eius dolorem hic fugiat minus. Soluta hic, ipsam vitae ipsa quia aspernatur eaque.
        Magnam alias dicta aspernatur saepe quos nesciunt nihil, perspiciatis eius, ad id laudantium veritatis praesentium. Maiores in minima odit repellendus saepe molestias, voluptatum quasi perspiciatis omnis sunt beatae facilis dolore.
        Omnis ex labore, eum sint ea quisquam expedita modi consequatur iusto recusandae minus laudantium maxime exercitationem tempora provident minima dolore numquam doloremque voluptatibus rem et. Commodi veniam harum quae placeat.
        Laborum tempore ut et aliquam ratione asperiores ducimus fugit sit aperiam porro qui delectus tenetur amet aliquid accusamus magnam sunt, provident consectetur minima? In autem dolores repellat tempora reiciendis atque!
        Impedit inventore aspernatur consectetur molestias fugit accusamus non nostrum quam mollitia quaerat, voluptates similique sequi suscipit corrupti cupiditate magni hic labore molestiae iusto eveniet perspiciatis. Magni enim rerum omnis. Officia?
        Culpa non magnam necessitatibus itaque consequuntur deleniti corporis quidem doloribus maxime totam sed minus nam libero officiis optio velit, id corrupti quo similique quia, ullam placeat accusantium sunt? Similique, tempora.
        Iusto debitis dolore recusandae ut cum magni atque, harum minima beatae aperiam est aliquid sunt sint quae voluptas fugiat exercitationem, commodi rem repellendus non consectetur! A maiores ullam nobis molestias.
        Aut earum maxime in porro accusantium sequi placeat quos vel illo architecto blanditiis explicabo modi eaque, quod recusandae? Dolorem repudiandae unde tempore quam architecto delectus blanditiis excepturi aspernatur nihil quis?
        Possimus alias dolor quasi ipsum, molestias vitae cum ad error recusandae ex sint maiores eos quibusdam sit atque saepe nam maxime? Corrupti cum provident dolorem obcaecati incidunt, dolor maxime totam.
        Non, ipsum! Iusto sint voluptas laborum mollitia, rem debitis culpa adipisci rerum nihil, reiciendis doloribus deserunt dolor corporis voluptatibus cupiditate fugit. Nobis, libero nemo quas cum incidunt eligendi at quisquam.
        Vel dicta necessitatibus expedita distinctio nam quae ipsa illo, eos iste. Qui minus, tempore ea voluptate illum omnis! Deleniti aspernatur officiis nostrum animi quisquam corrupti possimus, dicta laboriosam. Ea, animi.
        Quibusdam architecto, inventore eaque voluptatem dicta, atque nisi accusantium molestias cupiditate facilis itaque eligendi sapiente aliquid, cumque debitis dolores doloremque iure dolorum. Quam nesciunt architecto harum fugit repudiandae voluptates dolores!
        Quos nihil minus facere voluptates ipsa ipsam ut, odit magnam et accusamus unde eveniet eligendi tenetur recusandae quibusdam vero debitis dolorem. Possimus illum earum illo exercitationem numquam. Excepturi, dolor inventore?
        A hic cupiditate, voluptatibus illum nostrum voluptatum, quidem quia tempora, optio in minus alias. Earum incidunt quidem, accusantium, dolore quas minima sit eos laudantium quod sapiente nesciunt animi aperiam quae!
        Commodi incidunt ipsa fugit, voluptates iure, pariatur dolores autem harum id quae quos soluta, aspernatur tenetur? Provident illo delectus quaerat laborum corporis repellat blanditiis tempora inventore? Omnis quod ab nesciunt?
        Illo, sit quasi. Nemo, totam excepturi eligendi, atque quae exercitationem eos ut, perferendis harum modi et aperiam saepe debitis nostrum tempora! Dicta quia tempore nostrum autem molestias aut quaerat voluptatibus.
        Rem, quam eligendi? Accusamus, quaerat, ab quidem voluptatum laboriosam tempora voluptates veniam numquam quod, unde at? Odio obcaecati dolore dolorum iure voluptatibus totam? Excepturi facere velit iure! Officia, architecto non.
        Ullam cum consectetur voluptates aspernatur, itaque facilis aliquid sint doloribus pariatur sunt unde quia voluptatum quae dolorum eligendi officia accusantium provident adipisci a ut numquam voluptatibus fuga impedit nesciunt? Animi?
        Magni quasi hic quam ipsum quo sit consectetur ad. Sunt vitae, voluptates, omnis a error enim odit rem corporis perspiciatis in dolorum, ullam obcaecati? Ipsa unde illum ipsam nihil nostrum?
        Voluptatibus enim, quisquam ipsum fugit numquam natus! Voluptas, atque adipisci! Odit fuga repellendus expedita quidem accusamus qui perspiciatis ipsum iste natus sit! Voluptatum nobis fugiat dicta perferendis iste recusandae doloremque.
        Fugiat, natus nesciunt veritatis inventore numquam explicabo eius. Id minus mollitia, nam sapiente neque ipsam velit accusantium autem laborum, dolor quibusdam blanditiis? Perspiciatis magnam ullam facere molestiae? Exercitationem, ea molestiae.
        Porro delectus repudiandae alias nemo, ea, veritatis dolor qui quam in, voluptate nihil culpa numquam cum soluta! Debitis qui fugit aut hic accusantium nesciunt animi, enim porro? Incidunt, assumenda nemo?
        Laboriosam sunt nihil voluptatem, totam eligendi dolorum, officiis quos officia aliquam ipsa nobis consequuntur at numquam velit atque vero. Minima nihil nostrum fuga necessitatibus voluptate repudiandae incidunt expedita quam porro.
        Veritatis culpa deleniti eos nulla at similique consequatur aspernatur natus ad, alias atque blanditiis? Temporibus commodi quo voluptatem magni cupiditate omnis doloribus, dolore consequuntur deserunt facere! Id iste itaque cumque.
        Illum asperiores optio itaque hic minima illo nobis doloribus ea dolor alias, dolores nulla enim voluptates, quibusdam dolore corrupti ducimus a laborum non maiores, voluptate explicabo laudantium architecto eligendi? Eum!
        Perspiciatis quae officiis minus obcaecati, vero quidem suscipit deleniti corporis similique facere. Ullam enim voluptatum, iusto error expedita obcaecati, quibusdam illum id, odio consectetur incidunt neque eveniet ad architecto quisquam?
        Alias nobis voluptatem fugit beatae dolor odio at dicta itaque magni inventore, velit atque, repellendus, quae tenetur a aliquam tempore quis delectus nemo facilis? Totam, nostrum? Quaerat ipsam sunt eius!
        Fuga officia aliquid quisquam sapiente dolorem officiis neque! Ratione quis recusandae distinctio quasi, placeat maxime totam necessitatibus voluptate. Sed quia amet ex repudiandae non quibusdam ut, corrupti debitis quod mollitia.
        Inventore et vel voluptate amet nemo dolore saepe itaque tenetur cupiditate accusantium repellendus harum perspiciatis ipsa sint eveniet iusto ipsum molestiae, labore, velit magni excepturi. Nihil iusto dicta nobis possimus.
        Ratione ipsa cumque numquam praesentium harum hic doloribus quas unde, dolorum fugit voluptas earum. Animi sit suscipit natus itaque ipsa provident in, voluptates praesentium! Exercitationem veritatis quaerat consequatur necessitatibus facere.
        Praesentium dolorum rem facilis fugit totam quaerat magni enim debitis tenetur sequi, expedita reprehenderit sed maxime eaque exercitationem sit inventore temporibus adipisci nostrum aliquam odio porro sapiente? Neque, natus minima.
        Similique atque quam nemo dolore et veritatis unde omnis sunt optio, consequuntur odio magni tempore nisi placeat dolores deleniti necessitatibus dicta deserunt quidem nobis! Nostrum consequatur error voluptas harum illum?
        Quod quis necessitatibus excepturi deleniti illo cum fugit sunt, corrupti laudantium libero maxime magni possimus neque sequi. Eum, hic? Molestias odit molestiae ad consequuntur eum? Sed dolore nulla officiis sit.
        Magnam, aut sit laboriosam maiores possimus obcaecati eius ex magni dolorem, hic tenetur corrupti quis iusto quibusdam facilis repellat, tempore illo totam nisi reprehenderit quas alias eum. Nostrum, enim illum!
        Ad ipsa assumenda aspernatur veniam deserunt ut esse temporibus blanditiis, magni unde. Nemo asperiores autem, iste maxime, facilis dolorem expedita veniam nam omnis blanditiis libero. Asperiores nulla commodi libero minima?
        Omnis minus aut assumenda quibusdam rem eius nihil perferendis, quaerat, totam excepturi commodi! Velit deserunt, officiis, illum, ut tempore excepturi delectus sunt dolor voluptas voluptate quam culpa molestias iure nulla?
        Laudantium excepturi possimus delectus ipsam voluptatum, accusantium sunt sequi optio sed ullam magni, minus repudiandae quaerat laboriosam tempora doloribus dolorum harum dicta itaque exercitationem blanditiis eum molestias nihil? Debitis, laborum!
        Temporibus labore commodi est, illo eligendi libero ipsum vel similique soluta vitae tempora ex quibusdam consequatur, distinctio cumque exercitationem et dicta voluptatibus quo optio facere ea ullam doloribus mollitia. Vel.
        Dicta iste at fugit similique iure deserunt eos facilis modi! Laboriosam explicabo modi blanditiis commodi, nihil saepe repellendus debitis suscipit autem illo quasi culpa obcaecati tenetur voluptatibus, eius cupiditate eligendi?
        Nihil consequuntur omnis nobis, in, voluptatum quos possimus explicabo consectetur mollitia laudantium perferendis ullam ut. Similique modi assumenda sed? A placeat labore aperiam voluptates, laboriosam sint quo non quis voluptatem!
        Ad id recusandae reprehenderit cum amet obcaecati tenetur, provident eum vero illum, illo necessitatibus temporibus eaque blanditiis impedit. Molestias dignissimos enim natus temporibus nesciunt consectetur porro magnam tenetur laborum omnis!
        Nemo sunt quidem voluptatibus repudiandae, deleniti inventore aspernatur dolorum hic aperiam praesentium ex minus. Reiciendis ad eum dolores hic fuga? Cumque itaque similique nulla error officia molestiae porro dolorum cum!
        Enim distinctio debitis animi ducimus nisi in, mollitia libero sapiente a sed optio corrupti esse asperiores perferendis dolorem consectetur, vel praesentium officia quasi? Odio error autem dolores saepe sint numquam.
        Rerum minima qui ipsa voluptate, ad quaerat earum, ut debitis adipisci odio eum. Vero laudantium rerum, fugit debitis aut quaerat ullam sunt odit possimus dolorum laboriosam quae consequuntur alias tenetur.
        Eveniet harum fugiat distinctio praesentium iusto impedit consequuntur ex sunt qui, commodi totam, veniam ipsam labore. Natus adipisci porro impedit. Tempora, expedita voluptas ad hic nihil blanditiis. Vel, ex officiis.
        Provident odit qui tenetur, dolor voluptates aut officiis perferendis eum laboriosam. Quia nemo dicta, quae id mollitia natus quasi. Quibusdam iste voluptatibus provident cupiditate ex ducimus? Sed quae vitae minus?
        Harum consequuntur atque alias non, in quisquam sequi delectus aliquid nobis facere, numquam accusantium architecto cupiditate mollitia sapiente, suscipit asperiores earum odio exercitationem veniam dolor voluptatem ratione vel culpa? Aspernatur.
        Itaque aliquam cumque accusantium, animi cupiditate possimus doloribus et pariatur fuga assumenda quidem libero provident aliquid id, qui voluptate autem tempore sit ipsum facere magni laboriosam. Unde iusto obcaecati molestias!
        Nesciunt vero provident dignissimos, dolor quaerat voluptatem consectetur numquam, rem soluta doloribus laborum totam. Expedita a quos magni laudantium eligendi libero atque quae minima nulla maxime officia, aliquid, aspernatur ex.
        Minima facere quod voluptatem pariatur quae distinctio beatae animi expedita dolores nostrum. Inventore expedita ut odit, nihil sed eaque magnam dolorum rem ex, nisi iure adipisci atque earum accusamus autem!
        Iure deleniti non cumque odit, fuga aliquam placeat enim quo, corporis iusto sed assumenda quod, ab inventore esse cupiditate quia doloremque adipisci exercitationem nesciunt tempore quibusdam fugit! Vero, molestiae modi?
        Fuga dolores dolor, officiis architecto iure, provident, laboriosam similique nemo enim distinctio repellendus eum veritatis illum ea natus odio molestiae rerum. Asperiores blanditiis officia facilis magni voluptatem, iure dolor doloribus!
        Itaque, quia ab? Atque error dolorum libero eligendi accusamus nihil nobis cumque expedita ut similique, id pariatur labore autem corrupti quos deserunt eveniet amet architecto esse quod quasi. Quasi, eos.
        Culpa tempore aspernatur quaerat eveniet sapiente debitis iste quasi, blanditiis autem nostrum. Laborum, maxime necessitatibus. Sunt tempore, expedita itaque culpa nostrum reiciendis quisquam impedit unde quasi a at ratione voluptatem?
        Ipsam, laborum doloribus esse recusandae autem iste tempora beatae vitae, ad eos reiciendis, numquam ratione iusto! Asperiores autem dolores expedita accusantium! Voluptas facere vel quidem dolorum nemo! Magni, nulla dolorem.
        Assumenda eligendi pariatur, ab sed amet officia minima asperiores odit itaque consectetur consequuntur, nemo, accusantium rem temporibus ratione nesciunt adipisci doloribus. Repudiandae at excepturi, repellat hic quo molestias. Sed, molestiae.
        Repellat ipsa sequi laboriosam, soluta veritatis pariatur nostrum dolorem iste autem quis reprehenderit quos quod, numquam nam provident neque architecto. In alias deserunt vel accusantium cum sapiente molestias repellendus saepe.
        In facere deleniti error non beatae eaque id nostrum cupiditate ipsum numquam rerum, quasi sunt provident iure culpa porro reprehenderit quae atque, sit molestiae quisquam dicta? Dignissimos, nemo assumenda. Eius!
        Omnis necessitatibus blanditiis laborum vero minima perferendis cum voluptates laudantium quibusdam doloribus, eum sit iure esse! At nisi ipsum possimus beatae recusandae neque magni necessitatibus reprehenderit dolor, ratione ea sit!
        Illo animi quam quasi, mollitia possimus vel facilis doloribus excepturi, placeat ipsum dolores molestiae debitis deserunt consequuntur tempore quod eveniet distinctio voluptatem at nobis cupiditate ad temporibus! Corporis, error provident?
        Minus, animi deleniti omnis saepe iusto eos! Aut ipsam harum, illo expedita libero commodi veniam inventore quisquam. Iure impedit necessitatibus repudiandae maiores doloribus rerum quo ducimus quod sit tempora. Rerum.
        Qui, officiis quibusdam. Esse ratione cumque saepe? Quas reiciendis eius expedita, sed voluptas quod a maxime pariatur reprehenderit delectus nisi. Eos, sunt? Earum tenetur tempora quisquam voluptate minima. Incidunt, eius?
        Iste at hic cum similique nesciunt sint architecto consequatur quis, fugit voluptate libero quidem ipsum neque, facere ipsa nemo, mollitia cumque ex numquam dolor eos perspiciatis? Error fugiat rerum voluptatum!
        Voluptatem, minima aut ab officiis nam incidunt odit enim quibusdam repellat sed qui distinctio libero numquam, voluptate veritatis. Voluptates numquam atque reprehenderit eius sed odit quo vitae, nostrum beatae quod!
        Veniam optio aliquid repellat vitae ipsam deserunt inventore laborum omnis dignissimos suscipit quas exercitationem, temporibus tempore hic dolore cum eaque quis alias in rerum repellendus itaque. Est minus tempora temporibus.
        Ex, voluptas aspernatur? Perspiciatis ducimus veritatis libero iste rerum temporibus nihil accusamus ipsa, nulla nobis sit voluptates minus veniam perferendis odit quidem voluptate. Similique nesciunt magnam quidem facere, adipisci aliquid.
        Exercitationem molestias explicabo, optio ut nulla rem quis ipsa numquam, dolorum consequatur impedit corporis sequi assumenda! Adipisci quae quaerat veniam, maxime a excepturi dicta corrupti qui consequuntur pariatur veritatis facere?
        Tempora sapiente dolores blanditiis, corporis nemo soluta delectus provident, dolor qui minima nihil expedita recusandae ducimus ratione! Eum iusto quisquam minus tenetur, aliquam, blanditiis illum quaerat atque repellendus totam architecto.
        Eaque corrupti nam vel libero delectus facilis. Aliquam iure itaque impedit quidem aut, sapiente autem ipsa culpa quis quibusdam? Voluptates alias aspernatur consequatur id. Id nesciunt exercitationem esse quisquam sunt?
        Aliquam harum, non ab impedit quae perspiciatis labore minus sunt minima quasi quisquam repudiandae architecto. Dignissimos aliquid impedit reprehenderit a non voluptatem tenetur dolor maiores numquam porro, quis similique? Neque.
        Explicabo a atque inventore labore ea tenetur veritatis cupiditate repudiandae amet velit, sapiente eligendi delectus quas harum consectetur doloremque autem provident? Atque voluptatem recusandae dolores cupiditate reiciendis, porro dolor dignissimos.
        Error explicabo libero sed quibusdam minima odio assumenda placeat aliquam? Itaque odio cupiditate fugit corporis vitae magni atque molestias quis. Molestiae ut ex repudiandae eligendi ea vitae sunt perspiciatis esse.
        Optio qui delectus debitis ab numquam, earum ut in, sequi incidunt ex, suscipit quasi eos nisi consequatur. Delectus eaque, minima sapiente, cupiditate molestias dolore error earum ad illo ut in.
        Asperiores culpa dolore pariatur, sapiente quia est harum dicta in porro quaerat iste officia! Enim iusto nostrum quaerat quia alias, possimus labore repellendus quisquam repudiandae atque voluptate similique iste necessitatibus?</p>
      <p className="scroll-result">{scrollTop}</p>
    </div>
  )
}

export default Position